# Generated by Django 4.1.5 on 2023-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
